baseURL = "/"
languageCode = "en-us"
title = "Philip Rosenberg-Watt"
theme = "hugo-resume"
relativeURLs = true
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

#publishDir = "/keybase/private/philrw,kbpbot/philip.rosenberg-watt.com"
#publishDir = "/Users/prosenberg-watt/Documents/Sync/personal-website"

[params]
    firstName = "Philip"
    lastName = "Rosenberg-Watt"
    address = "Superior, CO"
    phone = "+13033255192"
    contactNote = "Software Engineer"
    profileImage = "images/me.jpg"
    email = "philip@rosenberg-watt.com"
    description = "Software Unicorn, Philomath, and Polymath"
    favicon = "images/favicon.ico"
    showQr = true
    showContact = true
    showCertifications = false
    showSocializations = true
#    sections = ["skills","publications","creations","contributions","experience","education","blog"]
    sections = ["skills","creations","contributions","experience","education"]

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/philiprosenbergwatt/"
    icon = "linkedin"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/PhilRW"
    icon = "github"

[[params.handles]]
    name = "Mastodon"
    link = "https://mastodon.rosenberg-watt.com/@philrw"
    icon = "mastodon"

[[params.handles]]
    name = "Cal"
    link = "https://cal.rosenberg-watt.com/philrw"
    icon = "calendar"


[outputs]
    home = ["HTML", "JSON"]
